Add remark field
AY2021S2-CS2103-W16-3/tp pull request #110
Opened 2021-03-15 09:03 UTC by Ellevy

Added optional Remark field for contacts as a String.
Constraints used are same as Address field.

Yet to update UI to display remark as command output. Remark currently displayed in the person card (along with the address, birthday, phone number, email, tags). 

Fixes #97

2021-03-15 12:36 UTC, pyuxiang requested changes
Other than the minor typos, LGTM!

2021-03-15 12:36 UTC, pyuxiang commented on src/main/java/seedu/partyplanet/logic/parser/ParserUtil.java
> +     * Parses a {@code String remark} into a {@code remark}.
```suggestion
     * Parses a {@code String remark} into a {@code Remark}.
```

2021-03-15 12:36 UTC, pyuxiang commented on src/main/java/seedu/partyplanet/logic/parser/ParserUtil.java
> +     * @throws ParseException if the given {@code remark} is invalid.
```suggestion
     * @throws ParseException if the given {@code Remark} is invalid.
```

2021-03-15 14:36 UTC, pyuxiang submitted a review, later dismissed
Nice

2021-03-16 04:06 UTC, zhengruoxin requested changes
Just a missing space, LGTM!

2021-03-16 04:18 UTC, pyuxiang commented on src/main/java/seedu/partyplanet/model/person/Remark.java
> +    public static final String MESSAGE_CONSTRAINTS = "Remark can take any values, and it should not be blank";
Perhaps best of both worlds: "You can write anything in the remarks, as long as it is not blank".

2021-03-16 11:16 UTC, garyljj commented on src/main/java/seedu/partyplanet/model/person/Remark.java
> +    public static final String MESSAGE_CONSTRAINTS = "Remark can take any values, and it should not be blank";
I think she was following the wording of constraint for address field. Should we change that too? or leave both

2021-03-16 11:24 UTC, garyljj approved these changes
LGTM

2021-03-16 11:36 UTC, zhengruoxin approved these changes

2021-03-16 11:36 UTC, merged