Add Find, Tags, List - Sort Features
AY2021S2-CS2103-W16-3/tp pull request #86
Opened 2021-03-09 13:06 UTC by glennljs

Closes #4, new issue will be opened to implement BDAY sort after birthdays are implemented.

2021-03-09 14:11 UTC, garyljj requested changes
Mostly minor stuff, just some style and naming changes

2021-03-09 14:11 UTC, garyljj commented on src/main/java/seedu/address/logic/parser/TagsCommandParser.java
> +        Optional<String> keyword = argMultimap.getValue(PREFIX_FIND);
just to standardise with other parser classes if you want haha 

```suggestion
        ArgumentMultimap argMultimap = ArgumentTokenizer.tokenize(args, PREFIX_FIND);
        
        Optional<String> keyword = argMultimap.getValue(PREFIX_FIND);
        
        if (keyword.isEmpty() && argMultimap.getPreamble().isEmpty()) {
            return new TagsCommand(tag -> true);
        }
```

2021-03-10 06:06 UTC, pyuxiang commented on src/main/java/seedu/address/logic/commands/FindCommand.java
> +            + "Example: " + COMMAND_WORD + "-n Bob -t CS2030";
Missing space.

```suggestion
            + "Example: " + COMMAND_WORD + " -n Bob -t CS2030";
```

2021-03-10 09:16 UTC, glennljs commented on src/main/java/seedu/address/logic/commands/FindCommand.java
> +            + "Parameters: [-n NAME] [-t TAGS]...\n"
Added in latest commit, multiple tags shouldn't be allowed, but can start an issue to add that functionality.

2021-03-10 09:18 UTC, glennljs commented on src/main/java/seedu/address/logic/commands/TagsCommand.java
> +    public static final String COMMAND_WORD = "tags";
This one I not sure but I think because the purpose is to list all tags then tags is better?

2021-03-10 09:20 UTC, glennljs commented on src/main/java/seedu/address/logic/commands/TagsCommand.java
> +                tags.compute(t, (k, v) -> v == null ? 1 : v + 1)));
Adopted in latest commit.

2021-03-10 09:30 UTC, glennljs commented on src/main/java/seedu/address/logic/commands/FindCommand.java
> +            + "Example: " + COMMAND_WORD + "-n Bob -t CS2030";
Adopted in latest commit.

2021-03-10 10:03 UTC, garyljj commented on src/main/java/seedu/hippocampus/logic/commands/TagsCommand.java
> +            + "person tagged in Hippocampus."
Add new line
```suggestion
            + "person tagged in Hippocampus.\n"
```

2021-03-11 17:18 UTC, garyljj approved these changes
LGTM

2021-03-12 06:19 UTC, Ellevy approved these changes
LGTM

2021-03-12 06:20 UTC, merged