Implement InputHistory
AY2021S2-CS2103-W16-3/tp pull request #92
Opened 2021-03-11 17:32 UTC by garyljj

closes #87

2021-03-11 18:58 UTC, nickyfoo requested changes
Besides the typo, LGTM

We might want to add documentation for this as well, can put up as an issue when we merge this, if we deem it necessary

2021-03-11 18:58 UTC, nickyfoo commented on src/main/java/seedu/hippocampus/commons/util/InputHistory.java
> +        if (lst.isEmpty() || isDifferentFromLastest(s)) {
```suggestion
        if (lst.isEmpty() || isDifferentFromLatest(s)) {
```

2021-03-11 18:58 UTC, nickyfoo commented on src/main/java/seedu/hippocampus/commons/util/InputHistory.java
> +    private boolean isDifferentFromLastest(String s) {
```suggestion
    private boolean isDifferentFromLatest(String s) {
```

2021-03-12 04:59 UTC, pyuxiang approved these changes
Easy to review, LGTM. For optimization, can consider using a ring buffer instead of a linked list.

2021-03-12 06:21 UTC, nickyfoo approved these changes

2021-03-12 10:45 UTC, merged