Update README and InputHistory in UserGuide
AY2021S2-CS2103-W16-3/tp pull request #96
Opened 2021-03-13 11:25 UTC by garyljj

Update README.md to PartyPlanet
Added InputHistory function details to UserGuide.md
Mainly:
- Up/down arrow cycles through history
- Esc clears input

2021-03-13 11:33 UTC, zhengruoxin commented on docs/UserGuide.md
> +* Pressing `Up` arrow key in the text input panel reverts to eariler input.
```suggestion
* Pressing `Up` arrow key in the text input panel reverts to earlier input.
```

2021-03-13 11:34 UTC, zhengruoxin requested changes
Just a typo, LGTM!

2021-03-13 11:34 UTC, zhengruoxin commented on docs/UserGuide.md
> +* At the most recent input, `Down` arrow key once more clears the text box.
```suggestion
* At the most recent input, pressing `Down` arrow key once more clears the text box.
```

2021-03-13 11:34 UTC, zhengruoxin commented on docs/UserGuide.md
> +* Pressing `Up` arrow key in the text input panel reverts to eariler input.
```suggestion
* Pressing `Up` arrow key in the text input panel reverts to earlier input.
```

2021-03-14 06:03 UTC, pyuxiang approved these changes
LGTM

2021-03-14 07:46 UTC, zhengruoxin approved these changes

2021-03-14 07:46 UTC, merged